### ISSUE TITLE
Unique Items/Item Locations Counter

### ISSUE THREAD

**Issue by MainMemory** [tommadness/KH2Randomizer#117]
I think it would be neat to have something visible in the randomizer that shows how many unique items (important checks, weapons, Sora abilities, key items, anything that must be placed somewhere to make a seed) there are, and how many item locations (chests, popups, bonuses, puzzle rewards, etc) are available based on the options you have selected. You could even have each world tell you how many item locations are in it in a tooltip.
![image](https://user-images.githubusercontent.com/6082665/169675594-5e3cafef-e89f-4afd-8eca-c6c27a2bd89b.png)

**Comment by zlittlefield** [comment]
I hope this will satisfy the request. Coming in the next generator update
![image](https://user-images.githubusercontent.com/16296574/169947606-4d6df40f-bcb6-4fd1-b0fe-648223e430b5.png)

**Comment by MainMemory** [comment]
Yeah!
