### ISSUE TITLE
Worlds can be double-hinted in JSmartee hint system

### ISSUE THREAD

**Issue by tommadness** [tommadness/KH2Randomizer#21]
Example:

[randoseed_20.zip](https://github.com/tommadness/KH2Randomizer/files/6612389/randoseed_20.zip)

Worlds can be hinted twice by different reports. Seems to be introduced by PR #19

Tagging @zlittlefield . If you have time to take care of this, that would be appreciated. If not, I will handle it over the weekend.

**Comment by zlittlefield** [comment]
On it. I'll look into why that happened.

**Comment by tommadness** [comment]
Corrected in #22
