### ISSUE TITLE
Enabling promise charm bug

### ISSUE THREAD

**Issue by zlittlefield** [tommadness/KH2Randomizer#27]
https://github.com/tommadness/KH2Randomizer/blob/e55271a24bbbef4f3d87556909a6f590a91fc3d9/Module/randomize.py#L66

I believe that line should be assigning the `validItemList` variable since the member variable version is overwritten below. That should allow the item to be placed. I'll try to test and put up a PR with this change

**Comment by snelson3** [comment]
@zlittlefield are you still planning to make a PR for this change? I can take it if you are not, but if you want it's a good opportunity to get things set up for contributing

**Comment by zlittlefield** [comment]
I can put it up. I've been doing a bunch of things that I probably need to split out into multiple pull requests. I was hoping to get that up today.

**Comment by snelson3** [comment]
Sounds good, I was just checking since the weekend is my time to work on
stuff
