### ISSUE TITLE
Option to make spoiler log only available to person generating seed

### ISSUE THREAD

**Issue by paulblessing** [tommadness/KH2Randomizer#57]
Would be a nice feature for whoever rolls a seed for a league/tournament race. Maybe send a hidden POST param when hitting Submit Query from the main page to distinguish the person generating the seed compared to someone who was given a link (if the site doesn't already know that information some other way via the session or something)?

Potential ideas to handle things past that:

- Create two separate permalinks, one permalink that configures the Generate buttons to generate zips with spoiler log included, and one permalink that doesn't. The person rolling the seed can choose which permalink to share depending on whether it's a tournament/league or a casual race.
- Generate the spoiler log as a separate file/zip file rather than including it with the seed. The person generating the seed just always gets an additional button/link to download the spoiler log and can choose to download and share it if they want. That would potentially eliminate the need for a Generate Spoiler Log toggle on the main page altogether.

**Comment by tommadness** [comment]
I like this idea, a sort of "Tournament Organizer" mode.

An added consideration: This setting should be made obvious to racers as well. Maybe prefixing the seed hash with `TOURNEY` or something. I'd be concerned with a bad actor turning this mode on for a race seed, having access to the spoiler log, but the other racers are unaware.

**Comment by zlittlefield** [comment]
A racer making a seed for a race could easily make a spoiler log for their seed, rezip every file but the spoiler and distribute that seed, so there is already a method for bad actors to hide a spoiler. I do like the idea of somehow giving the organizer access to the spoiler log. Maybe by appending the seed hash with a tourney key phrase that the organizer adds when making the seed? (going with the first option). Or the second file is encrypted with a key the organizer provides. Idk, just trying to offer other ideas

**Comment by o0DemonBoy0o** [comment]
in addition to this, i believe also changing the .hints file name to be something other than the seed name would be helpful too, as anybody could just grab the seed from that and recreate it to make their own spoiler log.

**Comment by zlittlefield** [comment]
Not possible to get the spoiler of a seed that wasn't generated with the spoiler log, since the seed provided will get changed internally if the spoiler log generation is enabled. But I agree that changing the hint file name may make that process more difficult.
