### ISSUE TITLE
Feature: Include a "Roll new seed with same settings" button on seed page

### ISSUE THREAD

**Issue by jhobz** [tommadness/KH2Randomizer#69]
The use cases here have some overlap with custom presets, but I think there are some distinct enough ones to warrant addition. As a player it would be helpful to me to simply press one button to generate a new random seed from the same settings as one I've already generated. That way if I want to practice with some specific settings, I don't need to return to the home page and re-enter the settings every time. It would also help for people looking at spoilers before playing their seed, in case they're trying to look for a specific scenario to practice.

**Comment by tommadness** [comment]
Effectively implemented in offline seed generator
