### ISSUE TITLE
No Keyblade Abilities Hang

### ISSUE THREAD

**Issue by MainMemory** [tommadness/KH2Randomizer#84]
Right now, unchecking "Support Keyblade Abilities" and "Action Keyblade Abilities" causes the seed generation to hang indefinitely. If it's possible, it would be neat to be able to have no abilities tied to keyblades; if not, the program should probably display a warning message.

**Comment by zlittlefield** [comment]
Keyblade abilities are getting reworked in the 2.0 version. If keyblades don't get abilities, then you may overflow the allowed memory for abilities, which messes with growth abilities and may cause instability. So instead, you will be able to restrict which abilities can't be on keyblades, and if too many are removed, then a seed won't generate.  Hopefully this addresses your concern.

**Comment by MainMemory** [comment]
Yes, that sounds great, thank you for the response!

**Comment by MainMemory** [comment]
I'll go ahead and close this since the latest builds have the new system in place.
