### ISSUE TITLE
First/Second Visit option allows report on Terra

### ISSUE THREAD

**Issue by paulblessing** [tommadness/KH2Randomizer#90]
I assume the "spirit" of the setting is that Terra would get grouped with datas for First/Second Visit and shouldn't be able to have a report with that depth. Below is a seed that has a report on Terra. Probably also worth looking into whether the Proof Depth option has the same issue (if it's deemed to be not working as intended).

2.0.0-beta.1.24$3gJRoPtVx7zZche0oVSvzGryF2RlWu$1$0-0-0-0-0-0-0-1-0-0-0-0-0-1-4-1-1-0-2-2--7-0-0123456789ABCDEFGHIJKLMNOPQRSTUVWXY-0-0-1-6-1-4-0--0-0-3-9-7-1-B-1-5-0-5-0-2-0-0-0-0-0-0-3-1-0-06-1-0-2-0123-1-C-1-4-0123456789ABCDE-1

**Comment by zlittlefield** [comment]
Yeah, the depth setting should really be called something like "no superbosses" and should also exclude Sephiroth as well (which I don't think it does currently). I'll work on a solution

**Comment by zlittlefield** [comment]
Hopefully this is fixed and has intended behavior now. If we discover that I haven't actually fixed this, I'll revisit.
