### ISSUE TITLE
Feature: "Stackables" Option for Ability Pool Randomization

### ISSUE THREAD

**Issue by MainMemory** [tommadness/KH2Randomizer#92]
Basically, this option would ensure that one of every ability is included in the pool, and then the remaining slots will be filled with random selections from abilities that have an effect when stacked (MP Haste, Fire Boost, Draw, Drive Converter, etc).

**Comment by zlittlefield** [comment]
I think this is very close to the randomize support abilities only option, so I'm going to close this issue, but if that's not quite was you were requesting, feel free to open a new issue or dm me on discord.
